<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="simplee" nsURI="simpleE" nsPrefix="simplee">
  <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
    <details key="invocationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
    <details key="settingDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
    <details key="validationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="Atributos" eSuperTypes="#//SimpleER">
    <eStructuralFeatures xsi:type="ecore:EReference" name="keys" upperBound="-1" eType="#//Keys"
        eOpposite="#//Keys/atributos"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isMultivalued" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//PrimaryType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Entidades" eSuperTypes="#//SimpleER">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="nombreAlMenos4letras unicaPK clavesAtributosPropios uniqueName attrNameUnique inherit PrimaryKeys"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="nombreAlMenos4letras" value="&#xA;&#x9;&#x9;&#x9;self.name.size() >= 4"/>
      <details key="unicaPK" value="&#xA;&#x9;    &#x9;self.claves-> select(c|c.oclIsKindOf(Primary_keys))-> size()=1"/>
      <details key="clavesAtributosPropios" value="&#xA;&#x9;    &#x9;self.claves->forAll(c | atributo->includesAll(c.atributos))"/>
      <details key="uniqueName" value="&#xA;&#x9;    &#x9;Entidades.allInstances()->forAll(e1,e2|e1&lt;>e2 implies e1.name &lt;> e2.name)"/>
      <details key="attrNameUnique" value="&#xA;&#x9;    &#x9;self.atributo->forAll(e1,e2 | e1 &lt;> e2 implies e1.name &lt;> e2.name)"/>
      <details key="inherit" value="&#xA;&#x9;    &#x9;(self.superclass &lt;> null) implies (self &lt;> self.superclass)"/>
      <details key="PrimaryKeys" value="&#xA;&#x9;    &#x9;((self.claves->select(c | c.oclIsKindOf(Primary_keys))->size())=0) implies self.superclass &lt;> null"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="atributo" upperBound="-1"
        eType="#//Atributos" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="claves" lowerBound="1"
        upperBound="-1" eType="#//Keys" containment="true" eOpposite="#//Keys/entidadKey"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="superclass" eType="#//Entidades"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Keys" eSuperTypes="#//SimpleER">
    <eStructuralFeatures xsi:type="ecore:EReference" name="atributos" lowerBound="1"
        upperBound="-1" eType="#//Atributos" eOpposite="#//Atributos/keys"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="entidadKey" lowerBound="1"
        eType="#//Entidades" eOpposite="#//Entidades/claves"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SimpleER" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Primary_keys" eSuperTypes="#//Keys"/>
  <eClassifiers xsi:type="ecore:EClass" name="BD" eSuperTypes="#//SimpleER">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="nombreUnico"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="nombreUnico" value="&#xA;&#x9;&#x9;&#x9;self.entidad -> forAll(e1,e2 | e1 &lt;> e2 implies e1.name &lt;> e2.name)"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="entidad" upperBound="-1"
        eType="#//Entidades" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="relacion" upperBound="-1"
        eType="#//Relacion" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Relacion" eSuperTypes="#//SimpleER">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="uniqueName attrNameUnique RelationName"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="uniqueName" value="&#xA;&#x9;    &#x9;Relacion.allInstances()->forAll(e1,e2|e1&lt;>e2 implies e1.name &lt;> e2.name)"/>
      <details key="attrNameUnique" value="&#xA;&#x9;    &#x9;self.atributos->forAll(e1,e2 | e1 &lt;> e2 implies e1.name &lt;> e2.name)"/>
      <details key="RelationName" value="&#xA;&#x9;    &#x9;Entidades.allInstances()->forAll(e | e.name &lt;> self.name)"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1"
        eType="#//Entidades"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="destination" lowerBound="1"
        eType="#//Entidades"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="atributos" upperBound="-1"
        eType="#//Atributos" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Cardinality" eType="#//Cardinality"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Cardinality">
    <eLiterals name="OneToOne" literal="1...1"/>
    <eLiterals name="OneToN" value="1" literal="1...N"/>
    <eLiterals name="NtoOne" value="2" literal="N...1"/>
    <eLiterals name="NtoN" value="3" literal="N...N"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="PrimaryType">
    <eLiterals name="String"/>
    <eLiterals name="Integer" value="1"/>
    <eLiterals name="Real" value="2"/>
    <eLiterals name="Datatime" value="3" literal=""/>
  </eClassifiers>
</ecore:EPackage>
